"""Configuration package: settings, roles, palettes and feature flags."""
from .settings import (
    AGGREGATIONS,
    CHART_TYPES,
    DATA_DIR,
    DB_PATH,
    LLM_MODELS,
    PALETTE,
    REPORT_DIR,
    RETAIL_ROLE_LABELS,
    RETAIL_ROLE_PATTERNS,
    RETAIL_ROLES,
    ROLE_LABELS,
    ROLE_PATTERNS,
    ROLES,
    ROOT_DIR,
    SAMPLE_DIR,
    UPLOAD_DIR,
    Settings,
    settings,
)

__all__ = [
    "AGGREGATIONS",
    "CHART_TYPES",
    "DATA_DIR",
    "DB_PATH",
    "LLM_MODELS",
    "PALETTE",
    "REPORT_DIR",
    "RETAIL_ROLE_LABELS",
    "RETAIL_ROLE_PATTERNS",
    "RETAIL_ROLES",
    "ROLE_LABELS",
    "ROLE_PATTERNS",
    "ROLES",
    "ROOT_DIR",
    "SAMPLE_DIR",
    "UPLOAD_DIR",
    "Settings",
    "settings",
]
